### ISSUE TITLE
error: could not find implicit value for parameter reader: pureconfig.Derivation[pureconfig.ConfigReader

### ISSUE THREAD

**Issue by charmby** [pureconfig/pureconfig#454] opened 2019-03-16 07:19 UTC
error: could not find implicit value for parameter reader: pureconfig.Derivation[pureconfig.ConfigReader

**Comment by ruippeixotog** [comment] 2019-03-17 12:07
Duplicate of #455.

**Closed as completed by ruippeixotog** 2019-03-17 12:07 UTC
