### ISSUE TITLE
Fix class duplicates

### ISSUE THREAD

**Issue by sentenza** [pureconfig/pureconfig#919] opened 2021-01-25 23:24 UTC
I'm using pureconfig `v0.14.0`. Running pantsbuild (v1.30.0) `detect-duplicates` multiple duplicates are detected:

```
$ ./pants detect-duplicates src/scala/myapp:main
...
 [detect-duplicates]

                    ===== For target JvmBinary(src/scala/com/eslgaming/services/gamehub/http4s_poc:main):
                   Duplicate classes and/or resources detected in artifacts: ('com.github.pureconfig-pureconfig-core_2.12-0.14.0.jar', 'com.github.pureconfig-pureconfig-macros_2.12-0.14.0.jar')
                        pureconfig/DerivationMacros$$anon$5.class
                        pureconfig/derivation/LazyContextParser.class
                        pureconfig/DerivationMacros$$typecreator2$1.class
                        pureconfig/DerivationMacros$$anon$1.class
                        pureconfig/derivation/LazyContextParser$LazyContext$.class
                        pureconfig/DerivationMacros$$anonfun$$nestedInanonfun$buildImplicitNotFound$1$1.class
                        pureconfig/Derivation$Successful$.class
                        pureconfig/derivation/LazyContextParser$LazyContextTree$$anon$2.class
                        pureconfig/derivation/MacroCompat$$typecreator1$1.class
                        pureconfig/Derivation$Successful.class
                        ... 20 more ...
                   Duplicate classes and/or resources detected in artifacts: ('com.github.pureconfig-pureconfig-generic-base_2.12-0.14.0.jar', 'com.github.pureconfig-pureconfig-generic_2.12-0.14.0.jar')
                        pureconfig/generic/CoproductHint$Attempt$.class
                        pureconfig/generic/CoproductHint$Use$.class
                        pureconfig/generic/error/CoproductHintException$.class
                        pureconfig/generic/ProductHint$Use.class
                        pureconfig/generic/ProductHint$Action.class
                        pureconfig/generic/ProductHint$UseOrDefault.class
                        pureconfig/generic/ProductHint$UseOrDefault$.class
                        pureconfig/generic/error/NoValidCoproductOptionFound$.class
                        pureconfig/generic/ProductHint$Use$.class
                        pureconfig/generic/ProductHintImpl.class
                        ... 18 more ...
```

Unfortunately, I cannot create a fat-jar if I have this kind of duplicates. 

This issue is related to https://github.com/pureconfig/pureconfig/issues/430. Also reported in https://github.com/pantsbuild/pants/issues/11488.

**Comment by sentenza** [comment] 2021-01-26 14:57
@leifwickland Do you have any clue why this happens?

**Comment by sentenza** [comment] 2021-02-26 11:53
@leifwickland I'm still trying to come up with a solution or a workaround for this issue. Do you have any clue?

**Comment by leifwickland** [comment] 2021-03-04 04:37
@sentenza, I'm sorry. I haven't had a chance to look at it. I'm afraid it won't happen this weekend either.

**Comment by leifwickland** [comment] 2021-04-27 20:07
@sentenza In pureconfig 0.15.x we've removed the macros package so half the pain is gone. The other half of the pain remains in `generic{,-base}`. I'm pretty sure that the duplication of `.class` files is due to the way that module uses the `SbtOsgi` module. Specifically `OsgiKeys.exportPackage := Seq("pureconfig.generic.*")` from https://github.com/pureconfig/pureconfig/blob/master/modules/generic/build.sbt#L15. I believe that is causing all `.class` files recursively under `pureconfig/generic/` to be included in the `pureconfig-generic.jar` regardless of which sub-project they were created from.

@ruippeixotog, @jcazevedo Does that explanation sound plausible to you?

I don't see an obvious way to fix this without moving the classes in `generic-base` to a new namespace, which would be a breaking change.

**Comment by ruippeixotog** [comment] 2021-05-01 22:56
I don't know how `pants`, `detect-duplicates` or even OSGi works but it looks like a plausible explanation, @leifwickland.

Moving `generic-base` classes to another package would be a breaking change and `generic` is the logical package for them to be. Maybe `generic-base` shouldn't have an OSGi annotation?

**Comment by leifwickland** [comment] 2021-05-03 05:15
@ruippeixotog Thanks for taking a look.  

I also don't know anything about OSGi or why we've got it.

I don't think the problem has anything to do with pants per se. I think you'd have the same problem using the sbt-assembly plugin if the default behavior were `MergeStrategy.singleOrError`. 

I created an sbt project that does nothing more than depend on `pureconfig-generic` and sets up the `sbt-assembly` plugin with a merge strategy that requires every file to be unique. 

At that point `sbt assembly` dumps a pile of errors like:

```
singleOrError: found multiple files for same target path:
/Users/lwickland/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-generic-base_2.13/0.15.0/pureconfig-generic-base_2.13-0.15.0.jar:pureconfig/generic/CoproductHint$.class
/Users/lwickland/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-generic_2.13/0.15.0/pureconfig-generic_2.13-0.15.0.jar:pureconfig/generic/CoproductHint$.class
singleOrError: found multiple files for same target path:
/Users/lwickland/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-generic-base_2.13/0.15.0/pureconfig-generic-base_2.13-0.15.0.jar:pureconfig/generic/CoproductHint$Action.class                                                              /Users/lwickland/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/github/pureconfig/pureconfig-generic_2.13/0.15.0/pureconfig-generic_2.13-0.15.0.jar:pureconfig/generic/CoproductHint$Action.class
```

I tried disabling the `SbtOsgi` plugin for generic base and then published a local snapshot. I updated the project I mentioned above to use that snapshot. I got the same errors because `pureconfig-generic-base*.jar` and `pureconfig-generic*.jar` still contain duplicate `class` files.

I think the root cause is that when we split generic into two jars to support magnolia, to preserve backward compat we didn't move any of the classes to new namespaces. Because of the way we're using osgi in `pureconfig-generic`, we're effectively make a "assembly" for the `pureconfig.generic.*` namespaces in the `pureconfig-generic*.jar` which doesn't play nicely with a strict build system that doesn't allow duplicate class files.

**Comment by ruippeixotog** [comment] 2021-05-10 20:44
@leifwickland the thing I don't understand, which seems related to OSGi, is that I'm used to have the package contents to be fully defined by the files included in SBT projects. Moving files from `pureconfig-generic` to `pureconfig-generic-base` shouldn't cause any trouble because the moved files shouldn't be included in `pureconfig-generic.jar` anymore. But my guess is that those OSGi settings are somewhat causing files from transitive dependencies to be included in the JAR too?

**Comment by leifwickland** [comment] 2021-05-12 21:03
@ruippeixotog, you said:

> But my guess is that those OSGi settings are somewhat causing files from transitive dependencies to be included in the JAR too?

Yes, I agree. That's my also impression.

Do you understand why we want the OSGi stuff? Could we simply remove it from the generic packages and get the behavior you and I are accustomed to where a jar only includes the class files that are in its directory within the sbt project?

**Comment by ruippeixotog** [comment] 2021-05-12 22:41
I searched a bit and this was one of the very first issues opened in this project (#4)! [Gathering](https://github.com/milessabin/shapeless/search?q=osgi) [some](https://github.com/typelevel/cats/search?q=osgi) [anectodal](https://github.com/circe/circe/search?q=osgi) [evidence](https://github.com/scalatest/scalatest/search?q=osgi) [around](https://github.com/akka/akka/search?q=osgi), it looks like the most popular Scala projects configure OSGi metadata. 

This plugin seems to be essential to use PureConfig in OSGi environments. While I would personally like to get rid of this, I'm a bit concerned that we might break PureConfig for some folks in a way that is non-trivial for them to fix. Do we have any concrete migration plan for those who need it?

(as a side note, when we add support for Scala 3 derivation in core (#1019) it's likely that `pureconfig-generic-base` will go away and the problem will be fixed by itself)

**Comment by leifwickland** [comment] 2021-05-12 22:54
@ruippeixotog In that case, I'll keep an eye on #1019 and make sure it solves this problem when it approaches the finish line.

**Comment by leifwickland** [comment] 2021-10-29 20:39
@ruippeixotog I happened to notice a discussion on Twitter today about OSGi modules.

https://twitter.com/mpilquist/status/1454177597668175873

Seth Tisue mentioned that they dropped OSGi from many scala modules and received no complaints, which makes me think we could probably get rid of them.

**Comment by ruippeixotog** [comment] 2021-10-31 00:04
That's a good insight @leifwickland, thanks for sharing! I guess it makes me a bit more comfortable removing OSGi support knowing that popular libraries did it too and got no complaints.

I know @jcazevedo is also on board with this, so I'll open a PR to do it.

**Closed as completed** 2021-10-31 12:33 UTC

**Comment by leifwickland** [comment] 2021-11-01 19:29
@sentenza Just to be explicit, this issue should be fixed. That said, we haven't published a release with the fix, yet.
