### ISSUE TITLE
[error] knownDirectSubclasses of ... observed before subclass ... registered

### ISSUE THREAD

**Issue by drewhk** [pureconfig/pureconfig#205] opened 2017-04-20 10:17 UTC
I have a simple ADT setup:

```
sealed trait KeyStoreLocation
  final case class Resource(path: String) extends KeyStoreLocation
  final case class File(path: String)     extends KeyStoreLocation
```

This type is used as a member of another case-class that I load via pureconfig. It seemed to work, but then after a while it stopped compiling:

```
[error] knownDirectSubclasses of KeyStoreLocation observed before subclass Resource registered
[error] knownDirectSubclasses of KeyStoreLocation observed before subclass File registered
```

What is weird that I have not changed any of the classes involved here! It seems like a compilation order issue to me, but I don't know how to fix it.

**Comment by tkroman** [comment] 2017-04-20 11:47
The workaround is to manually define the problematic implicit (the one this macro is trying to create). I've done this with upickle, which provides a way to do this semi-automatically, where you don't need to write the actual code but just specify the subclass parts for the root implicit (http://www.lihaoyi.com/upickle-pprint/upickle/#ManualSealedTraitPicklers). You could check if something like this might work for your case.

**Comment by drewhk** [comment] 2017-04-20 11:48
I assumed also that it can work but I was not able to figure out how I can manually create the implicit.

**Comment by melrief** [comment] 2017-04-21 12:41
Hey Drewhk, thanks for opening the issue. I'm trying to reproduce your error but I'm unable to trigger it.

The steps that I've followed are:

I opened a test REPL with

```
sbt core/test:console
```

I created the sealed trait:

```scala
@ {
    sealed trait KeyStoreLocation
    final case class File(path: String)     extends KeyStoreLocation
    final case class Resource(path: String) extends KeyStoreLocation
  }
```

Then checked if the `ConfigReader` was available, which it is:

```scala
@ pureconfig.ConfigReader[KeyStoreLocation] 
res3: pureconfig.ConfigReader[KeyStoreLocation] = pureconfig.DerivedReaders$$anon$8@14101287
```

Then I defined a class with a field of type `KeyStoreLocation` and checked again the `ConfigReader`, with no problems:

```scala
@ case class Foo(k: KeyStoreLocation) 
@ pureconfig.ConfigReader[Foo] 
res5: pureconfig.ConfigReader[Foo] = pureconfig.DerivedReaders$$anon$7@50d81ad9
```

Then tried to load the configuration via `loadConfig`, which worked:

```scala
@ import com.typesafe.config.ConfigFactory 
@ import pureconfig._ 
@ loadConfig[Foo](ConfigFactory.parseString("""{ k: { type: "file", path: "/foo/bar" } }""")) 
res9: Either[error.ConfigReaderFailures, Foo] = Right(Foo(File("/foo/bar")))
```

and finally I tried to load a wrong configuration, to see if the `ConfigReader` for coproducts was behaving correctly:

```scala
@ loadConfig[Foo] 
res6: Either[pureconfig.error.ConfigReaderFailures, Foo] = Left(ConfigReaderFailures(KeyNotFound("k", None), List()))
```

I'm unable to reproduce the error. What could help us understanding the issue is to see a minimal example of the issue, do you have a small example which triggers the error to share with us?

**Comment by drewhk** [comment] 2017-04-21 12:46
I will try to do a more extensive reproducer.

**Comment by sirthias** [comment] 2017-06-23 14:33
Nesting the ADT "cases" in the super types companion object, as is a popular name spacing technique, appears to trigger this problem.
For instance

```scala
sealed trait Foo
object Foo {
  case object AFoo extends Foo
  case object BFoo extends Foo
}
```

**Comment by leifwickland** [comment] 2017-06-23 16:48
@sirthias Would you please consider submitting a test case to reproduce? The EnumTest.scala would be a good place to start copying from.

**Comment by sirthias** [comment] 2017-06-26 13:39
Done: https://github.com/pureconfig/pureconfig/pull/278

**Comment by leifwickland** [comment] 2017-06-26 13:53
@sirthias Thanks!

**Comment by briangordon** [comment] 2017-09-11 02:06
Note for people who are googling this... this bug should be fixed in Scala 2.12.4 (scala/scala#6029)

In the meantime one easy workaround is to rename the file containing your ADT to have "AA" in front of the filename. That rejiggers the lexicographical order of the filenames and the compiler stops complaining.

**Comment by melrief** [comment] 2017-10-19 20:37
@briangordon if Scala 2.12.4 should fix this then we have an issue. The test submitted by @sirthias doesn't work even with Scala 2.12.4.

**Comment by ruippeixotog** [comment] 2017-10-19 22:15
@melrief it works, according to https://github.com/pureconfig/pureconfig/pull/317. The build is failing because it doesn't work in Scala 2.10 and 2.11 (obviosuly) and I forgot about that :(

**Comment by briangordon** [comment] 2017-10-23 00:57
After upgrading to 2.12.4 I no longer see this issue occurring in my project.

**Closed as completed** 2017-10-30 09:44 UTC
