### ISSUE TITLE
DurationConvert fails to convert Duration(8092048641075763L, TimeUnit.NANOSECONDS)

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#182] opened 2017-03-22 13:08 UTC
To reproduce:

```scala
"Converting a Duration from and to a String" should "return the Duration itself" in {
  val duration = Duration(8092048641075763L, TimeUnit.NANOSECONDS)
  fromS(fromD(duration)) shouldBe Right(duration)
}
```

with pureconfig `<= 0.6.0` the result of the test is

```
[info] - should return the Duration itself *** FAILED ***
[info]   Right(8092048641075764 nanoseconds) was not equal to Right(8092048641075763 nanoseconds) (DurationConvertSuite.scala:87)
```

I found this when I added tests for arbitrary `Duration` and `FiniteDuration` in #151.

**Comment by leifwickland** [comment] 2017-03-22 15:41
@melrief 
I think the behavior is caused by overflowing a `Double`.
When parsing a value from a `String`, Duration converts the magnitude to a `Double`.
See https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/duration/Duration.scala#L62
8092048641075763 is > 2^52, so precision is lost.

The comments there seem to indicate that they think precision won't be lost. However, some quick examples in the REPL seem to prove otherwise

```
scala> Duration("8092048641075763 ns")
res5: scala.concurrent.duration.Duration = 8092048641075764 nanoseconds

scala> Duration(8092048641075763d, NANOSECONDS)
res6: scala.concurrent.duration.Duration = 8092048641075764 nanoseconds
```

The bug is caused by adding `0.5` to the `Double` and then converting to a `Long` to round it, which normally works fine, but breaks when 2^52 < `length` < 2^53. 

See https://github.com/scala/scala/blob/2.11.x/src/library/scala/concurrent/duration/Duration.scala#L130

Example:
```
// Breaks
scala> (8092048641075763d + .5).toLong
res17: Long = 8092048641075764

// Works < 2^52
scala> (4503599627370492d + 0.5).toLong
res27: Long = 4503599627370492
```

I think this bug should be closed as will not fix because the root cause is weirdness in Scala's standard lib.

**Comment by leifwickland** [comment] 2017-03-22 16:03
It occurs to me will-not-fix isn't really an option because the behavior is manifesting in a scalacheck test. We have to change something. I'd be tempted to suggest we exclude values between +/- 2^52 to 2^53.

**Comment by melrief** [comment] 2017-03-23 12:50
@leifwickland from the generator? I've done it in #151 to avoid the issue, we should not merge PRs with flickering tests.

**Comment by leifwickland** [comment] 2017-03-23 16:11
@melrief Yeah, sorry for being unclear. Yes, I meant we should exclude  +/- 2^52 to 2^53 from the generator of values.

**Comment by leifwickland** [comment] 2017-04-27 20:42
Here's another randonly generated example that I stumbled across:
```
scala> Duration("4606485909763277 microseconds")
res1: scala.concurrent.duration.Duration = 4606485909763276800 nanoseconds
```

As was the case with the prior example, the scalar is between 2^52 and 2^53.

**Closed as completed** 2017-05-18 19:25 UTC
Labels: bug
