### ISSUE TITLE
ProductHint with allowUnknownKeys=false misbehaves

### ISSUE THREAD

**Issue by mslinn** [pureconfig/pureconfig#142] opened 2017-02-25 17:17 UTC
`ProductHint` with `allowUnknownKeys=false` misbehaves with `pureconfig.loadConfig` and `pureconfig.loadConfigOrThrow`.

I made a demo project to show the issue. [Here is the relevant section](https://github.com/mslinn/pure-config-test/blob/master/src/main/scala/PureConfigFun.scala#L18-L35). This code does not reference `application.conf` and should not try to pull in `reference.conf`.

    implicit val hint: ProductHint[PureConfigFun] = ProductHint[PureConfigFun](allowUnknownKeys = false)
    pureconfig.loadConfigOrThrow[PureConfigFun](Paths.get("pure.conf"))

Here is the error:

```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a value of class PureConfigFun. Failures are:
  Other failures:
    -  UnknownKey(path,None)
    -  UnknownKey(file,None)
    -  UnknownKey(java,None)
    -  UnknownKey(os,None)
    -  UnknownKey(line,None)
    -  UnknownKey(user,None)
    -  UnknownKey(sun,None)
    -  UnknownKey(akka,None)
    -  UnknownKey(awt,None)
```

My app does not contain `application.conf`. Based on the error message, it looks like PureConfig compares against `reference.conf`, instead of just looking at `pure.conf`.

**Comment by mslinn** [comment] 2017-02-25 17:38
Another weird thing: the `pure.conf` HOCON file has the configuration that should be mapped to the PureConfigFun case class [in the `"ew"` key](https://github.com/mslinn/pure-config-test/blob/master/src/main/resources/pure.conf#L1-L52). Seems like that key is somehow mapped without having to be specified, and if I do specify it, as shown in the following two examples, I get `com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ew'`.

    pureconfig.loadConfig[PureConfigFun](Paths.get("pure.conf"), "ew")

    pureconfig.loadConfigOrThrow[PureConfigFun](Paths.get("pure.conf"), "ew")

**Comment by melrief** [comment] 2017-02-25 22:02
Hi @mslinn, thanks for opening the issue! I'll need to have a look at the code first, I'll reply again as soon as I know what's going on.

**Comment by melrief** [comment] 2017-02-25 23:10
I found multiple issues that cause the problems that you are describing above:

First of all, I'm not sure if you moved `pure.conf` from `src/main/resources` to the working directory of where you are trying to load it but in my tests if I run `Files.exists(Paths.get("pure.conf"))` in `sbt console` I get `false`, which means that the file is not loaded. This explains your second error: the reason why `ew` is not found is because `pure.conf` is not even read. The only way that I know to take a `Path` from a resource is via `Paths.get(getClass.getResource("/pure.conf").getPath)`. In this case the file is loaded. A way to see this is to ask to pureconfig to give you back the original `ConfigValue` as loaded by typesafe config. Anyway, if you pass the right `Path`, loading works as expected:

```scala
scala> pureconfig.loadConfigOrThrow[ConfigValue](Paths.get("pure.conf"), "ew")
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ew'

scala> pureconfig.loadConfigOrThrow[PureConfigFun](Paths.get(getClass.getResource("/pure.conf").getPath), "ew")
pureconfig.error.ConfigReaderException: Cannot convert configuration to a value of class PureConfigFun. Failures are:
  Other failures:
    - (/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf:8) WrongTypeForKey(NUMBER,ConfigObject,ew.feed.port,Some(ConfigValueLocation(/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf,8)))
```

As you can see the error has changed because in the second case the file is loaded and typesafe config is able to find the namespace `"ew"`. Loading the raw `ConfigValue` as loaded by typesafe config is very helpful to debug file reading issues like this.
Note that the example still fails to load because `Port` is not `Int` but a value class wrapping `Int` and thus pureconfig expects a HOCON object at that point and not an `Int`. You may want to change port to `port = { value: 9090 }` so that it works:

```scala
scala> pureconfig.loadConfigOrThrow[PureConfigFun](Paths.get(getClass.getResource("/pure.conf").getPath), "ew")
res0: PureConfigFun = PureConfigFun(ConsoleConfig(true),FeedConfig(Port(9090)),ReplConfig(~),SpeciesConfig(0,100,25,20),SshServerConfig(true,,Port(1101)))
```

The second part is about all the unknown keys found by the system. The typesafe [`ConfigFactory.load`](https://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#load-com.typesafe.config.Config-) method loads the given file but also adds overrides and fallbacks. In particular, it reads the system environment and loads them into the `Config` returned. pureconfig will then find those keys in the `Config`. If you don't give any namespace to the `pureconfig.loadConfig` methods, pureconfig will basically give you back every single system property not involved in your class as unknow key failure. As for above, loading a raw `ConfigValue` is your friend to see what's going on and if you call `render` on it you can also see from where a certain configuration value has been loaded:

```scala
scala> pureconfig.loadConfigOrThrow[ConfigValue](Paths.get(getClass.getResource("/pure.conf").getPath)).render.lines foreach println
[...]
    "user" : {
        # system properties
        "country" : "US",
        # system properties
        "dir" : "/home/foo/prog/pure-config-test",
        # system properties
        "home" : "/home/foo",
        # system properties
        "language" : "en",
        # system properties
        "name" : "foo",
        # system properties
        "timezone" : "Europe/Bar"
   }
[...]
```

The solution to this problem is to either use `allowUnknownKeys = true` or to always use a namespace that you know won't contain anything else except the configuration you need. In this case, not even `"ew"` is enough because there are configuration keys that are not needed to load a `PureConfigFun`:

```scala
scala> pureconfig.loadConfigOrThrow[PureConfigFun](Paths.get(getClass.getResource("/pure.conf").getPath), "ew")
pureconfig.error.ConfigReaderException: Cannot convert configuration to a value of class PureConfigFun. Failures are:
  Other failures:
    - (/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf:17) UnknownKey(ew.speciesDefaults,Some(ConfigValueLocation(/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf,17)))
    - (/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf:31) UnknownKey(ew.sshServer,Some(ConfigValueLocation(/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf,31)))
```

But it's better than before.

I hope this has been helpful. If you need clarifications or you have more questions, we are here to help.

**Comment by mslinn** [comment] 2017-02-26 07:19
Thanks for your kindness. I appreciate it.

This works better under Windows:
```
lazy val confPath: Path = new java.io.File(getClass.getResource("pure.conf").getPath).toPath
def loadOrThrow: PureConfigFun = pureconfig.loadConfigOrThrow[PureConfigFun](confPath, "ew")
```
The code you showed dies when `Paths.get` encounters the colon after the Windows drive letter. For some reason the above does not die :)

BTW, there is no need to provide a path (`"/pure.conf"`) when a file is on the classpath.

After thinking about the `Port` value class problem, I understand the syntax you offered but I don't like it.

    port = { value: 9090 }

Is there any way for PureConfig to wrap simple types like `Int` and `String` into value classes? I'd like to use strong typing, but I don't want to fill the conf file with ugly weirdness like the above in order to achieve strong typing.

Thanks, Mike

**Comment by melrief** [comment] 2017-02-26 11:02
Hey Mike,

It seems that I cannot load `"/pure.conf"` using that relative path. Not sure why but it seems that it's working for you. Is pureconfig finding the `"ew"` namespace now? Or the problem is still there?

About value classes, the standard way to support new types with a different configuration syntax than the one proposed by pureconfig is to create your own `ConfigConvert`. I suggest to do that because adding this kind of `ConfigConvert` is trivial:

```scala
implicit val readPort = fromNonEmptyStringConvert[Port](catchReadError(str => Port(str.toInt)), _.value.toString)
```

This line tells pureconfig that you want to read `Port` from a `String` and that the converter can throw exception, which `catchReadError` will encapsulate in a nice error, and that the converter is `str => Port(str.toInt)`.
Eventually, the procedure of adding new converters from existing ones will be added (see #93) and covering the value classes use case will be as simple as writing `implicit val readIt = ConfigReader[Int].map(Port.apply)`. We are not there yet :-).

**Comment by mslinn** [comment] 2017-02-26 15:47
Loading `"/pure.conf"` is problematic. Loading `"pure.conf"` without the leading slash worked for me. Did you try that?

Glad to learn about `ConfigConvert`. I did not want to introduce an implicit conversion between `String` and `Path` because Scala would apply it indiscriminately.

A few discussion points remain outstanding. I'll play with the code and get back to you shortly.

**Comment by mslinn** [comment] 2017-02-26 16:13
I prefer to express a `Port` as a `Number` in the `conf` file, instead of `String`. However, there are currently no predefined `ConfigConvert`s from `Number`, just from `String`. I would like to use a `ConfigConvert` something like:

      val readPort: ConfigConvert[Port] =
        fromNumberConvert[Port](catchReadError(num => Port(num.toInt)), _.value)

What would be the best way to write `fromNumberConvert`?

**Comment by melrief** [comment] 2017-02-26 16:41
Similar to what we already have for `String`:

```scala
implicit val readPort = new ConfigConvert[Port] {
    override def from(config: ConfigValue): Either[ConfigReaderFailures, Port] = {
      config.valueType() match {
        case ConfigValueType.NUMBER =>
          Right(Port(config.unwrapped().asInstanceOf[Int]))
        case t =>
          fail(CannotConvert(config.render(), "Port", s"A port should be a number, but ${config.valueType()} has been found", ConfigValueLocation(config)))
      }
    }

    override def to(port: Port): ConfigValue = ConfigValueFactory.fromAnyRef(port.value)
}
```

**Comment by mslinn** [comment] 2017-02-26 16:54
Thanks, that is better than what I had attempted to write. I checked in what I have so far. Currently the errors are:

```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a value of class PureConfigFun. Failures are:
  Other failures:
    - (/var/work/experiments/config/pure-config-test/target/scala-2.12/classes/pure.conf:8) WrongTypeForKey(NUMBER,ConfigObject,ew.feed.port,Some(ConfigValueLocation(/var/work/experiments/config/pure-config-test/target/scala-2.12/classes/pure.conf,8)))
    - (/var/work/experiments/config/pure-config-test/target/scala-2.12/classes/pure.conf:17) UnknownKey(ew.speciesDefaults,Some(ConfigValueLocation(/var/work/experiments/config/pure-config-test/target/scala-2.12/classes/pure.conf,17)))
    - (/var/work/experiments/config/pure-config-test/target/scala-2.12/classes/pure.conf:31) UnknownKey(ew.sshServer,Some(ConfigValueLocation(/var/work/experiments/config/pure-config-test/target/scala-2.12/classes/pure.conf,31)))```

**Comment by melrief** [comment] 2017-02-26 16:58
It looks like it's not picking up the custom converter. It works for me. My guess without seeing the code is that you forgot to add `implicit` before `val` to make the custom converter visible. Otherwise, I'll need to see the code.

**Comment by mslinn** [comment] 2017-02-26 16:59
https://github.com/mslinn/pure-config-test/blob/master/src/main/scala/PureConfigFun.scala

**Comment by melrief** [comment] 2017-02-26 17:05
I've `git reset --hard` and `git pull` the last master of the example. When I run in `sbt console`

```scala
scala> pureconfig.loadConfigOrThrow[PureConfigFun](Paths.get("/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf"), "ew")
```

I don't get the error about `Port`, but only the issues with the unknown keys found:

```scala
pureconfig.error.ConfigReaderException: Cannot convert configuration to a value of class PureConfigFun. Failures are:
  Other failures:
    - (/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf:17) UnknownKey(ew.speciesDefaults,Some(ConfigValueLocation(/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf,17)))
    - (/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf:31) UnknownKey(ew.sshServer,Some(ConfigValueLocation(/tmp/sbt/home/mariop/prog/pure-config-test/scala-2.12/classes/pure.conf,31)))
```

I don't understand why the same example is behaving in a different way. Can you copy paste step-by-step what you are doing to obtain that message?

**Comment by mslinn** [comment] 2017-02-26 17:08
This is how I generate the errors:

    $ sbt "runMain PureConfigTest2"

Still wondering what I need to do in order to fix up the other errors.

**Comment by melrief** [comment] 2017-02-26 17:14
I see the issue: you define the `readPort` after the `load` method and the `load` method doesn't take in input the `ConfigConvert[PureConfFun]`, which means that `def load: Either[ConfigReaderFailures, PureConfigFun] = pureconfig.loadConfig[PureConfigFun](confPath, "ew")` will take the `ConfigConvert[PureConfFun]` when it's defined. `readPort` is defined after `load` and `load` doesn't see it. To fix, move `readPort` before `load` to get it instantiated before `load` is defined:

```scala
  implicit val readPort = new ConfigConvert[Port] {
    override def from(config: ConfigValue): Either[ConfigReaderFailures, Port] = {
      config.valueType() match {
        case ConfigValueType.NUMBER =>
          Right(Port(config.unwrapped().asInstanceOf[Int]))

        case t =>
          fail(CannotConvert(config.render(), "Port", s"A port should be a number, but ${ config.valueType } was found", ConfigValueLocation(config)))
      }
    }

    override def to(port: Port): ConfigValue = ConfigValueFactory.fromAnyRef(port.value)
  }

  def load: Either[ConfigReaderFailures, PureConfigFun] = pureconfig.loadConfig[PureConfigFun](confPath, "ew")
```

**Comment by melrief** [comment] 2017-02-26 17:20
For the `UnknownKey`s errors, the issue is that the default `fieldMapping` is `KebabCase`. See the [doc](https://github.com/melrief/pureconfig/blob/master/core/docs/override-behaviour-for-case-classes.md#override-behaviour-for-case-classes). But the keys in your configuration are `CamelCase`. To configure to use `CamelCase` as field mapping, change the `hint` to

```scala
implicit val hint: ProductHint[PureConfigFun] =
  ProductHint[PureConfigFun](
    allowUnknownKeys = false,
    fieldMapping = ConfigFieldMapping(CamelCase, CamelCase)
  )
```

And everything should work

```
sbt "runMain PureConfigTest2"
[info] Loading global plugins from /home/mariop/.sbt/0.13/plugins
[info] Loading project definition from /home/mariop/prog/pure-config-test/project
[info] Set current project to pure-config-test (in build file:/home/mariop/prog/pure-config-test/)
PureConfigFun(ConsoleConfig(true),FeedConfig(Port(9090)),ReplConfig(~),SpeciesDefaults(0,100,25,20),SshServer(localhost,/home/mariop,true,None,,Port(1101),repl))
[success] Total time: 16 s, completed Feb 26, 2017 6:18:56 PM
```

**Comment by mslinn** [comment] 2017-02-26 18:32
Yes! Learned some good things. Will update the ScalaCourses lecture.

**Comment by mslinn** [comment] 2017-02-26 20:29
I wonder if the converter you wrote for value classes might be made generic. The need to populate value classes from simple types is fundamental. Unrestrained converters are undesirable, so it would be best if converter boilerplate was eliminated by declaring them as required. Is there a way to define a `ConfigConvertValue` type which accepts the types to convert from and to? Here is how it might be used:

```
implicit val readIntValue = ConfigConvertValue[Int, Port]
implicit val readReplConfigValue = ConfigConvertValue[Path, ReplConfig]
```

The `ConfigConvertValue` implementation would subclass `ConfigConvert` in a similar way as you showed earlier.

**Comment by melrief** [comment] 2017-02-27 11:15
@mslinn we are going to provide a set of combinators to create new `ConfigConvert`s from old ones following roughly what many other libraries like `circe` and `scodec` do. I expect #93 to be solved in the next months.

**Comment by mslinn** [comment] 2017-02-27 17:34
Excellent!

**Comment by melrief** [comment] 2017-03-02 16:19
@mslinn I'm closing this as resolved

**Closed as completed by melrief** 2017-03-02 16:19 UTC
