### ISSUE TITLE
Fields with type Option[ComplexType] are always converted to None

### ISSUE THREAD

**Issue by zsolt-donca** [pureconfig/pureconfig#29] opened 2016-09-06 06:26 UTC
Fields with type `Option[ComplexType]` always seem to be converted to `None`.

Consider the below example. My intention is to configure the authentication needed to access a certain service. The service may or may not be configured to require authentication, which is a pair of username and password. Thus, my model is as follows.

Consider the following `.conf` file:

```
credentials {
  username = "admin"
  password = "secret"
}
```

And consider the following code:

```
import pureconfig._

case class Credentials(username: String, password: String)
case class Config(credentials: Option[Credentials])

object Main extends App {
    val config = loadConfig[Config].get
    println("Config: " + config)
}
```

When run, it wrongly prints:

```
Config: Config(None)
```

However, if I make the credentials mandatory, and thus I change the declaration of the `credentials` fields of `Config` class and remove the `Option` wrapper:

```
case class Config(credentials: Credentials)
```

Then, the code correctly prints: 

```
Config: Config(Credentials(admin,secret))
```

If the `credentials` section is missing altogether from the `.conf` file, then, the conversion correctly uses `None`. Also, if the type parameter of `Option` is a primitive type (number or `String`), then conversion seems to properly work. Only the conversion of `Option`s with complex types seems to be wrong, and the behavior seems to be always converting to `None`.

**Comment by melrief** [comment] 2016-09-06 17:39
I did a few tests and the issue is bigger than just `Option`: apparently there is a bug affecting all the type families that include an object, like `None`. I'm still unsure why this happens but I have an idea. I'll create a PR with the fix once I have an idea of how to fix it.

**Comment by melrief** [comment] 2016-09-15 20:01
PR #28 seems to fix this

**Comment by jcazevedo** [comment] 2016-09-29 01:15
I believe we can close this one.

**Comment by melrief** [comment] 2016-09-29 09:02
Closed, @zsolt-donca if you have again this problem we will reopen it

**Closed as completed** 2016-09-29 09:01 UTC
